version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    restart: always

  app:
    build: .
    environment:
      - EDITOR=vim
      - REDIS_URL=redis://redis:6379
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache:cached
      - bundle:/bundle:cached
    ports:
      - '8080:3000'
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  postgres:
  rails_cache:
  bundle: